base.url=https://practicesoftwaretesting.com/
api.base.url=https://api.practicesoftwaretesting.com

browser=chromium
headless=false
timeout=30000
slow.motion=200

auth.email=customer@practicesoftwaretesting.com
auth.password=welcome01

screenshot.on.failure=true
video.on.failure=false
trace.on.failure=true