name: UI Tests

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Install Playwright Browsers
        shell: cmd
        run: mvn exec:java -D"exec.mainClass=com.microsoft.playwright.CLI" -D"exec.args=install"

      - name: Run UI tests
        continue-on-error: true
        shell: cmd
        run: mvn clean test -Dtest=HomeTests,ProductTests,CartTests,AuthTests,CheckoutTests -Dheadless=false

      - name: Install Allure CLI
        if: always()
        shell: powershell
        run: |
          $progressPreference = 'silentlyContinue'
          Invoke-WebRequest -Uri "https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip" -OutFile "allure.zip"
          Expand-Archive -Path allure.zip -DestinationPath "C:\"
          echo "C:\allure-2.29.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Generate Allure HTML Report
        if: always()
        shell: cmd
        run: allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-allure-html-report
          path: target/allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-allure-results
          path: target/allure-results