name: UI Tests

on:
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Run UI tests
        shell: cmd
        continue-on-error: true
        run: mvn clean test -Dtest=HomeTests,ProductTests,CartTests,AuthTests,CheckoutTests -Dheadless=false

      - name: Add Allure to PATH
        if: always()
        shell: powershell
        run: |
          echo "C:\allure-2.29.0\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          C:\allure-2.29.0\bin\allure.bat --version

      - name: Generate Allure HTML Report
        if: always()
        shell: cmd
        run: C:\allure-2.29.0\bin\allure.bat generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-allure-html-report
          path: target/allure-report

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-allure-results
          path: target/allure-results